alertmanager:
  enabled: false

prometheus:
  service:
    type: LoadBalancer

grafana:
  enabled: true
  service:
    type: LoadBalancer
  adminUser: admin
  adminPassword: admin123
  persistence:
    enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
