alertmanager:
  enabled: false

prometheus:
  service:
    type: LoadBalancer
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-sc
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  enabled: true
  service:
    type: LoadBalancer
  adminUser: admin
  adminPassword: admin123
  persistence:
    enabled: true
    storageClassName: ebs-sc
    size: 2Gi

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true